zhongturtle term proposal
yungyuc/nsdhw_19au pull request #63
Opened 2019-10-27 12:44 UTC by zhongturtle

2019-10-28 13:46 UTC, yungyuc requested changes
The proposal is clear about what you want to do.  As long as you give a better scope about the project extent it's good to go.

2019-10-28 13:46 UTC, yungyuc commented on term_proposal/zhongturtle/proposal.md
> +## TO-DO List
You have many items in the list.  It seems to be too long if you want to do them all in the 2 months.  And be reminded that you need to demonstrate what you learn about software engineering during the course, which takes non-trivial effort.

Could you prioritize the todo items, before you move forward for the implementation?

2019-10-31 12:52 UTC, yungyuc commented
@zhongturtle before this can be merged, you need to change the target branch to be `term-proposal`, instead of `master`.

2019-11-07 13:06 UTC, yungyuc commented
@zhongturtle any update?

2019-11-09 08:29 UTC, yungyuc commented
@zhongturtle you need to merge against `term-proposal` branch, not `master`.

2019-11-10 17:01 UTC, zhongturtle commented
Sorry for the late reply, I have re-PR and add the priority of action items

2019-11-12 13:16 UTC, yungyuc commented
Thanks.  You are still merging against `master`.  It's not correct.  The PR should be against `term-proposal`.

2019-11-12 13:17 UTC, yungyuc approved these changes

2019-11-19 14:46 UTC, yungyuc commented
Merged https://github.com/yungyuc/nsdhw_19au/pull/72 instead.

2019-11-19 14:46 UTC, closed without merging